- name: demo on loops
  hosts: local
  connection: local
  tasks:
    - name: printing loops
      ansible.builtin.debug:
        msg: "{{item}}"
      loop:
      - Ramesh
      - raheem
      - john