- name: demo on loops
  hosts: local
  connection: local
  become: Yes
  tasks:
    - name: installing packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
      - nginx
      - mysql
      - zip